### PR TITLE
gcc compatibility

### PR DESCRIPTION
**Pull request by phoenix-de**
msp430-gcc does not know __even_in_range

### CODE REVIEW

**Comment by phoenix-de** [comment]
Comment on Schematics: 

R3 should be changed to 20k, because BSS123 has V_GS of 0.8 (min) to 2.0 (max).
When msp430 VCC is 3.3V, you have a gate voltage of only 1.65V with R4 and R3 at 10k, which does not work with every charge of BSS123 ... took me a while to figure out.

**Comment by vlad-ivanov-name** [comment]
> msp430-gcc does not know __even_in_range

There should be something like `#ifdef __GNUC__`. However, there's only one case so `if` is good enough too. I haven't tried it with GCC, thanks for testing!

**Comment by vlad-ivanov-name** [comment]
> you have a gate voltage of only 1.65V with R4 and R3 at 10k, which does not work with every charge of BSS123 ... took me a while to figure out.

Thank you! I have changed R4 value to 4.7k because it fits into standard resistor value series.

**Comment by phoenix-de** [comment]
Thanks for your work by the way! Really helpful for my home automation project.

**Comment by vlad-ivanov-name** [comment]
@phoenix-de since you're the one of a few people actually using this project, I think I need to share my experience with one-slave and home automation. I'm using this library for an OW-controlled LED dimmer for about 3 months now. I have 4 devices on the line: 
- 1x MSP430-emulated DS2408
- 2x original DS2408 connected to HD44780 displays
- 1x DS18B20

Every 5 minutes DS2408 display is updated with weather information. There is a problem — sometimes (about once a week) display text becomes corrupt. It only happens when MSP430 is connected to OW line. Also, correct display text is restored on the next display update. I'm not sure how this happens (data transfers contain CRC, how can they be corrupted in a first place?) and I don't know how to reproduce it. So the point is if you encounter some strange behaviour like I described above — please let me know by opening an issue, and we'll try to do something with it.

Thank you again for your feedback.

**Comment by phoenix-de** [comment]
@resetnow I will keep an eye on it thanks. I plan to modify the code a bit and will review it.
My intention is to use an additional wire as interrupt line for the host on port input changes to a) avoid constant polling and b) to have minimal delay when reading e.g. push-buttons.

already working quite well:
- DS2482S-800 I2C 8-channel 1-wire Master (on a raspberrypi)
- 5x DS2408 to switch blinds and lights, controlled by enocean wireless switches or tablet
- 18x DS2438Z with HIH 5030 humidity sensor, several DS18B20

planned additon:
- 2x MSP430 emulated DS2408 as output, with one uln2803 to switch relays, instead of two required for the open drain original DS2408, yay
- 4x MSP430 modified emulated DS2408 with "interrupt line" push-button input
- later on: MSP430 pwm for LED ambient lighting and underfloor heating valves
- add existing MSP430 which switches a ventilator based on a DHT22 humidty sensor to 1-wire network

It is a low priority spare time project, so it might take quite a while to contribute results.

**Comment by vlad-ivanov-name** [comment]
Wow, that's a lot of devices! Just out of curiosity, what do you use as a server software/UI?

**Comment by phoenix-de** [comment]
I saw you are contributing to openHAB, but i am more into python ;)
As a start I simply set up a djangoproject site with a few buttons and gauges and got 1-wire and enocean running in a couple of hours, thats why i love python.
But i don't want to reinvent the wheel, so i will try openHAB and Home Assistant.

**Pull request merged**
